name: test

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5

    - name: golangci-lint on main
      if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
      uses: reviewdog/action-golangci-lint@v2
      with:
        reporter: github-check
        filter_mode: nofilter
        fail_level: error

    - name: golangci-lint on PR
      if: ${{ github.ref_name != 'main' || github.event_name != 'push' }}
      uses: reviewdog/action-golangci-lint@v2
      with:
        reporter: github-pr-review
        filter_mode: diff_context
        fail_level: error

    - run: make test
